apiVersion: v1
kind: Pod
metadata:
  name: pod-with-dont-allow-privesc-cap-sys-admin
spec:
  containers:
  - name: pod-with-dont-allow-privesc-cap-sys-admin
    image: ctrsec/tools:latest
    securityContext:
      capabilities:
        add:
          - CAP_SYS_ADMIN
      allowPrivilegeEscalation: false